draw_set_valign(fa_center)
draw_set_halign(fa_center)
draw_set_font(font0)
draw_text_transformed_color(540,800,"Jejda! Příliš pozdě.\nVaše skóre je:",(0.66/size)*2,(0.66/size)*2,0,c_white,c_white,c_white,c_white,size-size2)
draw_text_transformed_color(540,1200,skore,(1.2/size)*2,(1.2/size)*2,0,c_white,c_white,c_white,c_white,size-size2)
draw_text_transformed_color(540,1540,"NOVÝ REKORD!",(0.5/size)*2,(0.5/size)*2,0,c_yellow,c_yellow,c_yellow,c_yellow,size-size2-hss)
draw_set_color(c_white)